sudo: false

language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --resolver lts-9.13 setup
- stack --no-terminal --version

branches:
  only:
    - diy

script:
  - travis_wait 180 stack --no-terminal blog.hs
  - rm -fr _site
  - mkdir -p _site/posts/
  - mv index.html _site/
  - mv *.html _site/posts/
  - cp -fr images _site/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: diy
