dist: xenial
language: node_js
node_js:
  - node

cache: npm

script:
  - npm run serve -- --ci

branches:
  only:
    - diy-ts

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: diy-ts
