# Site settings
title: Pythux
email: remi[dot]berson[at]gmail[you know what]com
description: > # this means to ignore newlines until "baseurl:"
    Yeah, you know... I mean. And much much more!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://remusao.github.io" # the base hostname & protocol for your site
twitter_username: Pythux
github_username: remusao
highlighter: pygments

# Build settings
markdown: kramdown

comments:
  provider: disqus
  disqus:
    short_name: remusaogithubio
